import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import https from 'node:https';
import os from 'node:os';
import path from 'node:path';

/**
 * Releases end to end (deployments spec §5 steps 3–8, §9): two apps — a
 * `dockerfile` app and a `static` app built with Node — on two domains with
 * `tls: internal`, both served by Caddy by Host header; a redeploy while
 * requests keep coming (none may fail); rollback; a config change that
 * switches the proxy to a new Caddy, again under load; a release failing its
 * health check while the old one keeps serving; pruning beyond
 * keep_releases; delete. Optionally a real Next.js app.
 *
 * Same throwaway server as deploy.integration.test.ts (`docker:dind` plus
 * `openssh-server` sharing the socket and the root), with the daemon's 443
 * published so the test can reach Caddy (never the host's own Docker):
 *
 *   docker network create bastion-rel-net
 *   docker volume create bastion-rel-sock && docker volume create bastion-rel-root
 *   docker run -d --rm --privileged --name bastion-rel-dind --network bastion-rel-net -e DOCKER_TLS_CERTDIR= \
 *     -p 127.0.0.1:28443:443 -v bastion-rel-sock:/var/run -v bastion-rel-root:/config/bastion docker:dind
 *   docker run -d --rm --name bastion-rel-sshd --network bastion-rel-net -p 127.0.0.1:28522:2222 \
 *     -e USER_NAME=smt -e USER_PASSWORD=bastion-it-pass -e PASSWORD_ACCESS=true -e PUID=1000 -e PGID=1000 \
 *     -v bastion-rel-sock:/sock -v bastion-rel-root:/config/bastion lscr.io/linuxserver/openssh-server
 *   docker exec bastion-rel-dind sh -c 'until [ -S /var/run/docker.sock ]; do sleep 1; done; chmod 666 /var/run/docker.sock; chown 1000:1000 /config/bastion'
 *   docker exec bastion-rel-sshd sh -c 'apk add --no-cache docker-cli && ln -sf /sock/docker.sock /var/run/docker.sock'
 *
 *   SMT_TEST_DEPLOY_SSH_HOST=127.0.0.1 SMT_TEST_DEPLOY_SSH_PORT=28522 SMT_TEST_DEPLOY_HTTPS=127.0.0.1:28443 \
 *     [SMT_TEST_DEPLOY_NEXTJS=1] pnpm vitest run src/deploy/release.integration.test.ts
 *
 *   docker stop bastion-rel-sshd bastion-rel-dind && docker volume rm bastion-rel-sock bastion-rel-root && docker network rm bastion-rel-net
 *
 * The daemon pulls busybox, node:20-alpine and caddy; the Next.js test also
 * installs next from the npm registry.
 */

const host = process.env.SMT_TEST_DEPLOY_SSH_HOST;
const port = Number(process.env.SMT_TEST_DEPLOY_SSH_PORT ?? 22);
const username = process.env.SMT_TEST_DEPLOY_SSH_USER ?? 'smt';
const password = process.env.SMT_TEST_DEPLOY_SSH_PASSWORD ?? 'bastion-it-pass';
const proxy = process.env.SMT_TEST_DEPLOY_HTTPS;
const nextjs = process.env.SMT_TEST_DEPLOY_NEXTJS === '1';

const { buildApp } = await import('../api/app.js');
const { runMigrations } = await import('../db/migrate.js');
const { seedOrg, seedUser } = await import('../api/routes/test-utils.js');

/** A .tar.gz of `files` (paths relative to the project root). */
function tarball(files: Record<string, string>): Buffer {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'bastion-rel-src-'));
  const src = path.join(dir, 'src');
  for (const [name, content] of Object.entries(files)) {
    fs.mkdirSync(path.dirname(path.join(src, name)), { recursive: true });
    fs.writeFileSync(path.join(src, name), content);
  }
  const file = path.join(dir, 'src.tar.gz');
  execFileSync('tar', ['czf', file, '-C', src, ...fs.readdirSync(src)], { env: { ...process.env, COPYFILE_DISABLE: '1' } });
  const data = fs.readFileSync(file);
  fs.rmSync(dir, { recursive: true, force: true });
  return data;
}

/** busybox httpd answering `body` on port 3000; /health only when `healthy`. */
const webSource = (body: string, healthy = true) =>
  tarball({
    Dockerfile: [
      'FROM busybox:1.36',
      `RUN mkdir /www && echo ${body} > /www/index.html${healthy ? ' && echo ok > /www/health' : ''}`,
      'CMD ["httpd", "-f", "-p", "3000", "-h", "/www"]',
      '',
    ].join('\n'),
  });

/** A static site generated by a Node build script (no dependencies, no lockfile). */
const docsSource = (body: string) =>
  tarball({
    'package.json': JSON.stringify({ name: 'docs1', private: true, scripts: { build: 'node build.mjs' } }),
    'build.mjs': `import fs from 'node:fs';\nfs.mkdirSync('dist', { recursive: true });\nfs.writeFileSync('dist/index.html', ${JSON.stringify(`<h1>${body}</h1>\n`)});\n`,
  });

/** One HTTPS request to Caddy for `domain` (SNI and Host), on a fresh connection. */
function get(domain: string, urlPath = '/'): Promise<{ status: number; body: string }> {
  const [hostname, p] = proxy!.split(':') as [string, string];
  return new Promise((resolve, reject) => {
    const req = https.request(
      { hostname, port: Number(p), path: urlPath, servername: domain, headers: { host: domain }, rejectUnauthorized: false, agent: false, timeout: 10_000 },
      (res) => {
        let body = '';
        res.setEncoding('utf8');
        res.on('data', (c: string) => (body += c));
        res.on('end', () => resolve({ status: res.statusCode ?? 0, body: body.trim() }));
        res.on('error', reject);
      },
    );
    req.on('timeout', () => req.destroy(new Error('timed out')));
    req.on('error', reject);
    req.end();
  });
}

/** Requests `domain` back to back until stopped; every failure (error or non-200) is kept. */
function hammer(domain: string) {
  let running = true;
  const bodies = new Set<string>();
  const failures: string[] = [];
  let count = 0;
  const loop = async () => {
    while (running) {
      try {
        const res = await get(domain);
        count++;
        if (res.status === 200) bodies.add(res.body);
        else failures.push(`HTTP ${res.status}: ${res.body.slice(0, 100)}`);
      } catch (err) {
        failures.push((err as Error).message);
      }
    }
  };
  const workers = [loop(), loop()];
  return {
    async stop() {
      running = false;
      await Promise.all(workers);
      return { bodies, failures, count };
    },
  };
}

describe.skipIf(!host || !proxy)('releases against a live server: builds, zero-downtime switches, health checks, pruning', () => {
  let app: Awaited<ReturnType<typeof buildApp>>;
  let base: string;
  let admin: ReturnType<typeof seedUser>;
  let serverId: string;
  const released: Record<string, string> = {};

  const api = (method: 'GET' | 'POST' | 'PUT' | 'DELETE', url: string, payload?: object) =>
    app.inject({ method, url, headers: admin.headers, ...(payload && { payload }) });
  const deployApi = (p = '') => `/api/deploy/servers/${serverId}${p}`;

  async function stream(url: string, init: RequestInit): Promise<Array<Record<string, unknown>>> {
    const res = await fetch(`${base}${url}`, { ...init, headers: { ...admin.headers, ...(init.headers as Record<string, string>) } });
    expect(res.headers.get('content-type'), await res.clone().text().catch(() => '')).toBe('text/event-stream');
    return (await res.text())
      .split('\n\n')
      .filter((b) => b.startsWith('data: '))
      .map((b) => JSON.parse(b.slice(6)) as Record<string, unknown>);
  }

  type Outcome = { release: string; previous: string | null; result: 'success' | 'failed'; error: string | null };

  async function deploy(appName: string, source: Buffer): Promise<{ outcome: Outcome; log: string }> {
    const form = new FormData();
    form.append('source', new Blob([source]), 'src.tar.gz');
    const events = await stream(deployApi(`/apps/${appName}/deploy`), { method: 'POST', body: form });
    const result = events.find((e) => e.type === 'result') as { outcome: Outcome } | undefined;
    const log = JSON.stringify(events.filter((e) => e.type === 'log'));
    expect(result, JSON.stringify(events).slice(-2000)).toBeDefined();
    return { outcome: result!.outcome, log };
  }

  async function rollback(appName: string, release: string): Promise<Outcome> {
    const events = await stream(deployApi(`/apps/${appName}/rollback`), {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ release }),
    });
    return (events.find((e) => e.type === 'result') as { outcome: Outcome }).outcome;
  }

  async function configure(appName: string, text: string) {
    const res = await api('PUT', deployApi(`/apps/${appName}/config`), { text });
    expect(res.statusCode, res.body).toBe(200);
  }

  const releases = async (appName: string) =>
    (await api('GET', deployApi(`/apps/${appName}/releases`))).json() as Array<{ id: string; current: boolean; result: string; imagePresent: boolean }>;

  beforeAll(async () => {
    await runMigrations();
    const orgId = seedOrg('release-it');
    admin = seedUser(orgId, 'admin');
    app = await buildApp();
    await app.listen({ port: 0, host: '127.0.0.1' });
    base = `http://127.0.0.1:${(app.server.address() as { port: number }).port}`;
    const res = await api('POST', '/api/servers', { name: 'release-it', host, port, username, authType: 'password', password });
    expect(res.statusCode, res.body).toBe(201);
    serverId = res.json().id;
    const setup = await api('POST', deployApi('/setup'));
    expect(setup.statusCode, setup.body).toBe(200);
  }, 300_000);

  afterAll(async () => {
    if (serverId) {
      for (const name of ['web1', 'docs1', 'next1']) await api('DELETE', deployApi(`/apps/${name}?purge=true`)).catch(() => {});
    }
    await app?.close();
  });

  it('deploys a dockerfile app and a static app, each served by Caddy on its own domain', async () => {
    await configure(
      'web1',
      'name: web1\ndomains: [web1.test]\ntls: internal\nbuild: { type: dockerfile }\nrun: { port: 3000 }\nhealthcheck: { path: /health, timeout: 15s }\nkeep_releases: 2\n',
    );
    await configure('docs1', 'name: docs1\ndomains: [docs1.test]\ntls: internal\nbuild: { type: static, output: dist }\n');

    const web = await deploy('web1', webSource('web-v1'));
    expect(web.outcome, web.log).toMatchObject({ result: 'success', previous: null });
    expect(web.log).toContain("Building with the project's Dockerfile");
    released.v1 = web.outcome.release;

    const docs = await deploy('docs1', docsSource('docs-v1'));
    expect(docs.outcome, docs.log).toMatchObject({ result: 'success' });
    expect(docs.log).toContain('Building a static site served by Caddy');
    expect(docs.log).toContain('Health check passed');

    expect(await get('web1.test')).toEqual({ status: 200, body: 'web-v1' });
    expect(await get('docs1.test')).toEqual({ status: 200, body: '<h1>docs-v1</h1>' });
    // A name no app serves gets no site (Caddy has no certificate for it)
    await expect(get('nobody.test')).rejects.toThrow();
  }, 900_000);

  it('switches to a new release without failing a single request', async () => {
    const load = hammer('web1.test');
    const { outcome, log } = await deploy('web1', webSource('web-v2'));
    // Keep requesting through the drain and removal of the old container
    await new Promise((r) => setTimeout(r, 2000));
    const { bodies, failures, count } = await load.stop();
    expect(outcome, log).toMatchObject({ result: 'success', previous: released.v1 });
    // No proxy reload: the new container joined the live alias, the old one stopped after the drain
    expect(log).toContain('Proxy config unchanged; traffic moves over the live network');
    expect(log).toContain('Both releases serve for');
    released.v2 = outcome.release;
    expect(failures, `${failures.length} of ${count} requests failed`).toEqual([]);
    expect(count).toBeGreaterThan(20);
    expect([...bodies].sort()).toEqual(['web-v1', 'web-v2']);
    expect(await get('web1.test')).toEqual({ status: 200, body: 'web-v2' });
    // The other app was never touched
    expect(await get('docs1.test')).toEqual({ status: 200, body: '<h1>docs-v1</h1>' });
  }, 900_000);

  it('rolls back to the kept image, again without a failed request', async () => {
    const load = hammer('web1.test');
    const outcome = await rollback('web1', released.v1!);
    await new Promise((r) => setTimeout(r, 2000));
    const { failures, count } = await load.stop();
    expect(outcome).toMatchObject({ result: 'success', release: released.v1, previous: released.v2 });
    expect(failures, `${failures.length} of ${count} requests failed`).toEqual([]);
    expect(await get('web1.test')).toEqual({ status: 200, body: 'web-v1' });
  }, 300_000);

  it('switches the proxy to a changed config without failing a single request', async () => {
    const load = hammer('web1.test');
    const docsLoad = hammer('docs1.test');
    // A second domain changes the Caddyfile: the front starts a new Caddy and moves new connections to it
    await configure(
      'web1',
      'name: web1\ndomains: [web1.test, web1-alt.test]\ntls: internal\nbuild: { type: dockerfile }\nrun: { port: 3000 }\nhealthcheck: { path: /health, timeout: 15s }\nkeep_releases: 2\n',
    );
    await new Promise((r) => setTimeout(r, 2000));
    const web = await load.stop();
    const docs = await docsLoad.stop();
    expect(web.failures, `${web.failures.length} of ${web.count} requests to web1 failed`).toEqual([]);
    expect(docs.failures, `${docs.failures.length} of ${docs.count} requests to docs1 failed`).toEqual([]);
    expect(web.count).toBeGreaterThan(20);
    expect([...web.bodies]).toEqual(['web-v1']);
    expect(await get('web1-alt.test')).toEqual({ status: 200, body: 'web-v1' });

    // And back, the same way: the name is no longer served
    const again = hammer('web1.test');
    await configure(
      'web1',
      'name: web1\ndomains: [web1.test]\ntls: internal\nbuild: { type: dockerfile }\nrun: { port: 3000 }\nhealthcheck: { path: /health, timeout: 15s }\nkeep_releases: 2\n',
    );
    await new Promise((r) => setTimeout(r, 2000));
    const back = await again.stop();
    expect(back.failures, `${back.failures.length} of ${back.count} requests failed`).toEqual([]);
    await expect(get('web1-alt.test')).rejects.toThrow();
  }, 300_000);

  it('keeps the old release serving when the new one fails its health check', async () => {
    const load = hammer('web1.test');
    const { outcome, log } = await deploy('web1', webSource('web-broken', false));
    const { bodies, failures } = await load.stop();
    expect(outcome, log).toMatchObject({ result: 'failed', error: expect.stringMatching(/Health check failed after 15s/) });
    expect(log).toContain('the previous release keeps serving');
    expect(failures).toEqual([]);
    expect([...bodies]).toEqual(['web-v1']);
    expect(await get('web1.test')).toEqual({ status: 200, body: 'web-v1' });
    const list = await releases('web1');
    expect(list.find((r) => r.id === outcome.release)).toMatchObject({ result: 'failed', current: false, imagePresent: false });
    released.broken = outcome.release;
  }, 300_000);

  it('prunes releases and images beyond keep_releases, never the current or previous', async () => {
    const { outcome } = await deploy('web1', webSource('web-v3'));
    expect(outcome).toMatchObject({ result: 'success', previous: released.v1 });
    expect(await get('web1.test')).toEqual({ status: 200, body: 'web-v3' });
    // keep_releases: 2 keeps the newest two (broken, v3); v1 stays as previous; v2 goes with its image
    const list = await releases('web1');
    expect(list.map((r) => r.id)).toEqual([outcome.release, released.broken, released.v1]);
    expect(list.find((r) => r.id === released.v1)).toMatchObject({ imagePresent: true });
    expect(list.find((r) => r.id === outcome.release)).toMatchObject({ current: true, imagePresent: true });
  }, 300_000);

  it('explains how to enable standalone output for a Next.js app without it', async () => {
    await configure('next1', 'name: next1\ndomains: [next1.test]\ntls: internal\nbuild: { type: nextjs }\nrun: { port: 3000 }\nhealthcheck: { path: /, timeout: 60s }\n');
    const { outcome } = await deploy(
      'next1',
      tarball({ 'package.json': '{"name":"next1","private":true}', 'next.config.js': 'module.exports = {};\n' }),
    );
    expect(outcome).toMatchObject({ result: 'failed', error: expect.stringMatching(/output: 'standalone'/) });
  }, 300_000);

  it.skipIf(!nextjs)('deploys a real Next.js app from its standalone output', async () => {
    const { outcome, log } = await deploy(
      'next1',
      tarball({
        'package.json': JSON.stringify({
          name: 'next1',
          private: true,
          scripts: { build: 'next build', start: 'next start' },
          dependencies: { next: '15.5.4', react: '19.1.1', 'react-dom': '19.1.1' },
          engines: { node: '>=22' },
        }),
        'next.config.js': "module.exports = { output: 'standalone' };\n",
        'app/layout.js': 'export default function RootLayout({ children }) { return <html><body>{children}</body></html>; }\n',
        'app/page.js': "export const dynamic = 'force-dynamic';\nexport default function Page() { return <h1>next-v1 {process.env.NODE_ENV}</h1>; }\n",
      }),
    );
    expect(outcome, log.slice(-3000)).toMatchObject({ result: 'success' });
    expect(log).toContain('Building Next.js (standalone) with npm');
    expect(log).toContain('node:22-alpine');
    const res = await get('next1.test');
    expect(res.status).toBe(200);
    expect(res.body).toMatch(/next-v1 (<!-- -->)?production/);
  }, 1_500_000);

  it('deletes the apps and takes them out of the proxy', async () => {
    for (const name of ['web1', 'docs1', 'next1']) {
      const res = await api('DELETE', deployApi(`/apps/${name}?purge=true`));
      expect(res.statusCode, res.body).toBe(200);
    }
    expect((await api('GET', deployApi('/apps'))).json()).toEqual([]);
    await expect(get('web1.test')).rejects.toThrow();
  }, 300_000);
});
