import { describe, it, expect } from 'vitest';
import { classifyCommand } from './command-safety.js';

const readOnly = [
  'ls -la /var/log',
  'cat /etc/os-release',
  'df -h',
  'free -m',
  'uptime',
  'uname -a',
  'hostname -f',
  'whoami && id',
  'ps aux | head -20',
  'ps aux --sort=-%mem | head -n 10',
  'top -b -n 1 | head -15',
  'top -bn1',
  'du -sh /var/* 2>/dev/null | sort -rh | head',
  'grep -i error /var/log/syslog | tail -50',
  "grep -rn 'listen' /etc/nginx/",
  'tail -n 100 /var/log/nginx/error.log',
  "find /var/log -name '*.log' -mtime -1",
  'find . -type f -size +100M',
  'stat /etc/passwd',
  'file /bin/ls',
  'wc -l /etc/passwd',
  'cut -d: -f1 /etc/passwd | sort | uniq -c',
  "sed -n '1,20p' /etc/fstab",
  "sed 's/foo/bar/g' config.txt",
  "sed -n -e '/error/p' app.log",
  'journalctl -u nginx --since "1 hour ago" --no-pager',
  'journalctl -p err -n 50',
  'dmesg -T | tail',
  'systemctl status nginx',
  'systemctl --no-pager status nginx',
  'systemctl is-active postgresql',
  'systemctl list-units --type=service --state=running',
  'systemctl --type=service list-units',
  'docker ps -a',
  'docker logs --tail 100 web',
  'docker stats --no-stream',
  'docker container ls',
  "docker inspect --format '{{.State.Status}}' web",
  'ip a',
  'ip addr show eth0',
  'ip route',
  'ip -br link show',
  'ss -tulpn',
  'netstat -tlnp',
  'lsof -i :80',
  'lsblk',
  'mount',
  'getent passwd root',
  'dig +short example.com',
  'nslookup example.com',
  'ping -c 3 8.8.8.8',
  'curl -I https://example.com',
  'curl -sS https://example.com/health',
  'curl -fsSL -H "Accept: application/json" https://example.com/api',
  'curl -X GET https://example.com',
  'git rev-parse --abbrev-ref HEAD',
  'git log --no-ext-diff --no-textconv --no-show-signature --oneline -n 10',
  'git -C /srv/app diff --no-ext-diff --no-textconv HEAD~1',
  'git branch -a',
  'git branch --list "feat/*"',
  'kubectl get pods -A',
  'kubectl -n prod describe deploy web',
  'kubectl logs web-123 --tail=50',
  'nginx -t',
  'apt list --installed',
  'dpkg -l | grep nginx',
  'rpm -qa',
  'crontab -l',
  'iptables -L -n -v',
  'sysctl net.ipv4.ip_forward',
  'date +%s',
  'env',
  'printenv PATH',
  'echo hello',
  'cd /var/log && ls -la',
  '/usr/bin/cat /etc/hostname',
  'ls 2>&1 | head',
  'cat nonexistent 2>/dev/null || echo missing',
  'ls >/dev/null',
  'grep -c x file &>/dev/null',
  'cat < /etc/hosts',
  'uptime; free -h; df -h',
  'grep "error$" app.log',
  'which nginx',
  'service nginx status',
  'echo $HOME',
];

const mutating = [
  'rm -rf /tmp/x',
  'reboot',
  'ls; rm -rf /',
  'ls && rm -rf /',
  'ls || rm -rf /',
  'ls | rm -rf /',
  'ls & rm -rf /',
  'ls\nrm -rf /',
  '(rm -rf /)',
  'cat x > y',
  'cat x >> y',
  'echo hi >y',
  'echo hi>y',
  'ls 2>err.log',
  'ls &>out.log',
  'ls >&out.log',
  'ls >| y',
  'cat <> y',
  'echo $(reboot)',
  'echo "$(reboot)"',
  'echo `reboot`',
  'cat <(reboot)',
  'find . -delete',
  'find / -name x -exec rm {} \\;',
  'find . -execdir rm {} +',
  'find . -fprint out.txt',
  "find . '-del''ete'",
  'find . -dele\\te',
  'find . ${X:=-delete}',
  "find . $'-delete'",
  'find *',
  "sed -i 's/a/b/' file",
  "sed -ni 's/a/b/p' file",
  "sed --in-place 's/a/b/' file",
  "sed 's/a/b/w out' file",
  "sed 's/a/b/e' file",
  "sed '1e reboot' file",
  'sed -f script.sed file',
  "awk '{print}' file",
  'systemctl restart nginx',
  'systemctl stop nginx',
  'systemctl -H host restart nginx',
  'curl -X POST https://example.com',
  'curl --request=DELETE https://example.com',
  'curl -d a=b https://example.com',
  'curl -o /tmp/x https://example.com',
  'curl -O https://example.com/file',
  'curl -T file https://example.com',
  'git branch -D main',
  'git branch -d feature',
  'git branch newbranch',
  'git -c core.pager=reboot log',
  'git log --output=/tmp/x',
  'git push',
  'git checkout main',
  'git tag v1',
  'sudo ls',
  'su -c ls',
  'doas ls',
  'echo hi | tee file',
  'ls | xargs rm',
  'eval ls',
  'exec ls',
  "sh -c 'ls'",
  "bash -c 'ls'",
  'X=1 ls',
  'env rm -rf /',
  './script.sh',
  '/tmp/evil/ls',
  'docker rm web',
  'docker stats',
  'docker -H tcp://x ps',
  'docker exec web ls',
  'kubectl delete pod web',
  'kubectl apply -f x.yaml',
  'ip link set eth0 down',
  'ip route add default via 10.0.0.1',
  'ip neigh flush all',
  'journalctl --vacuum-time=1d',
  'journalctl --rotate',
  'dmesg -c',
  'dmesg -C',
  'date -s "2020-01-01"',
  'date 010100002020',
  'hostname newname',
  'mount /dev/sdb1 /mnt',
  'sort -o out.txt in.txt',
  'sort --output=out in',
  'uniq in.txt out.txt',
  'tree -o out.txt',
  'less -o log.txt file',
  'file -C -m magic',
  'crontab -r',
  'crontab -e',
  'iptables -F',
  'iptables -L -Z',
  'sysctl -w net.ipv4.ip_forward=1',
  'sysctl net.ipv4.ip_forward=1',
  'sysctl -p',
  'nginx -s reload',
  'apt install nginx',
  'dpkg -i x.deb',
  'rpm -e pkg',
  'ping 8.8.8.8',
  'top',
  'cat <<EOF\nhi\nEOF',
  "echo 'unterminated",
  'service nginx restart',
  'chmod 777 /etc/passwd',
  'kill -9 1',
  'constructor',
];

/**
 * Regressions from the security review: each of these was classified read-only
 * before the fix.
 */
const reviewRegressions = [
  // A quote inside a comment made the tokenizer read the next line as quoted text
  "ls # it's fine\nrm -rf / #'",
  'ls #"\nreboot\n#"',
  'echo hi #',
  'ls >#x',
  // Generic `--name=value` leading options on subcommand programs
  'nft --file=/tmp/rules list ruleset',
  'nft list ruleset -f /tmp/rules',
  'dnf --installroot=/tmp/root list',
  'dnf --setopt=pluginpath=/tmp list',
  'yum --config=/tmp/yum.conf list',
  'yum list --downloaddir=/tmp',
  'dnf list -c /tmp/evil.conf',
  'systemctl --host=box status nginx',
  // `ss -K` kills sockets, `-D` dumps into a file
  'ss -K dst 10.0.0.1',
  'ss -tK',
  'ss --kill',
  'ss -D /tmp/dump',
  'ss --diag=/tmp/dump',
  // git diff drivers and textconv filters from repo config run programs
  'git diff',
  'git -C /srv/app diff HEAD~1',
  'git show HEAD',
  'git log -p',
  'git log --oneline -n 10',
  'git diff --no-ext-diff',
  'git diff --no-textconv',
  'git diff --no-ext-diff --no-textconv --ext-diff',
  'git diff --no-ext-diff --no-textconv --textconv',
  'git blame file.txt',
  'git --exec-path=/tmp status',
  // core.fsmonitor runs on index refresh; gpg.program runs to verify signatures
  'git status',
  'git ls-files',
  'git describe --dirty',
  'git shortlog -sn',
  'git blame --no-textconv file.txt',
  'git log --no-ext-diff --no-textconv --oneline -n 10',
  'git log --no-ext-diff --no-textconv --no-show-signature',
  'git show --no-ext-diff --no-textconv --oneline HEAD',
  'git log --no-ext-diff --no-textconv --no-show-signature --oneline --show-signature',
  "git log --no-ext-diff --no-textconv --no-show-signature --format='%h %G?'",
  'git log --no-ext-diff --no-textconv --no-show-signature --pretty=myalias',
  'git log --no-ext-diff --no-textconv --no-show-signature --oneline --format=myalias',
  'git show --no-ext-diff --no-textconv --no-show-signature --format=%GS HEAD',
  "git log --no-ext-diff --no-textconv --no-show-signature --format='%(describe)'",
  // the switches must lead: here `--grep` takes `--no-textconv` as its value
  'git log --no-ext-diff --no-show-signature --oneline --grep --no-textconv -p',
  'git diff HEAD -- --no-ext-diff --no-textconv',
  'git tag -l -v v1',
  "git tag -l --format='%(signature)'",
  "git branch --format='%(signature)'",
  // kubeconfig exec credential plugins run local programs
  'kubectl --kubeconfig /tmp/cfg get pods',
  'kubectl --kubeconfig=/tmp/cfg get pods',
  'kubectl get pods --kubeconfig=/tmp/cfg',
  'kubectl get pods --log-file=/tmp/x',
  'kubectl get -k ./overlay',
  // Expansions hide arguments from flag-sensitive rules
  'find . $X',
  'find . ${X}',
  'find . "$X"',
  'sed $S file',
  'git $SUB',
  'curl $URL',
  'ss $FLAGS',
  'journalctl $X',
];

const reviewStillReadOnly = [
  'git diff --no-ext-diff --no-textconv',
  'git -C /srv/app diff --no-ext-diff --no-textconv HEAD~1',
  'git log --no-ext-diff --no-textconv --no-show-signature --oneline -n 10',
  'git log --no-ext-diff --no-textconv --no-show-signature --oneline -p -n 1',
  "git log --no-ext-diff --no-textconv --no-show-signature --format='%h %an %s'",
  'git show --no-ext-diff --no-textconv --no-show-signature --format=medium HEAD',
  'git show --no-show-signature --pretty --no-textconv --no-ext-diff HEAD',
  'git rev-parse HEAD',
  'git tag -l "v1.*"',
  'git branch -vv',
  'nft list ruleset',
  'nft -a list ruleset',
  'dnf list --installed',
  'yum -q info nginx',
  'ss -s',
  'ss -tnp state established',
  "grep -c '#' file",
  'echo a#b',
  "find . -name '$X'",
  'echo $HOME',
  'cat "$HOME/.profile"',
  'kubectl -n prod get pods',
];

describe('classifyCommand', () => {
  it.each(readOnly)('treats %j as read-only', (cmd) => {
    const result = classifyCommand(cmd);
    expect(result, result.reason).toMatchObject({ mutating: false });
  });

  it.each(mutating)('treats %j as mutating', (cmd) => {
    expect(classifyCommand(cmd).mutating).toBe(true);
  });

  it.each(reviewRegressions)('treats %j as mutating (review regression)', (cmd) => {
    expect(classifyCommand(cmd).mutating).toBe(true);
  });

  it.each(reviewStillReadOnly)('still treats %j as read-only', (cmd) => {
    const result = classifyCommand(cmd);
    expect(result, result.reason).toMatchObject({ mutating: false });
  });

  it('explains the review-driven refusals', () => {
    expect(classifyCommand('ls # note').reason).toMatch(/comment/i);
    expect(classifyCommand('find . $X').reason).toMatch(/variable/i);
    expect(classifyCommand('git diff').reason).toMatch(/--no-ext-diff/);
    expect(classifyCommand('git status').reason).toMatch(/--no-show-signature/);
    expect(classifyCommand('git log').reason).toMatch(
      /--no-ext-diff --no-textconv --no-show-signature/,
    );
  });

  it('explains why a command needs approval', () => {
    expect(classifyCommand('ls; rm -rf /').reason).toMatch(/`rm` is not a known read-only command/);
    expect(classifyCommand('cat x > y').reason).toMatch(/redirects output into a file/i);
    expect(classifyCommand('echo $(reboot)').reason).toMatch(/command substitution/i);
    expect(classifyCommand('sudo ls').reason).toMatch(/elevated privileges/);
    expect(classifyCommand('find . -delete').reason).toMatch(/-delete/);
  });

  it('does not ask about an empty command (the tool rejects it anyway)', () => {
    expect(classifyCommand('   ').mutating).toBe(false);
  });
});
