import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';

/**
 * What the app hands a host that is being set up as a connectivity agent: the
 * single-file agent (built by packages/agent) and an install script that
 * fetches it, checks its hash, and runs it under systemd.
 *
 * The script is the same for every agent and carries no secret. The token is
 * passed in the environment of the one-off install command shown to the admin
 * and ends up only in /etc/bastion-agent/agent.env (root, mode 600).
 */

export const AGENT_BUNDLE_PATH = '/api/agents/bastion-agent.cjs';
export const AGENT_INSTALL_PATH = '/api/agents/install.sh';

export interface AgentBundle {
  code: Buffer;
  sha256: string;
}

let cached: AgentBundle | null | undefined;

/** The built agent, or null when packages/agent has not been built. */
export function agentBundle(): AgentBundle | null {
  if (cached !== undefined) return cached;
  try {
    const require = createRequire(import.meta.url);
    const dir = path.dirname(require.resolve('@smt/agent/package.json'));
    const code = readFileSync(path.join(dir, 'dist', 'bastion-agent.cjs'));
    cached = { code, sha256: createHash('sha256').update(code).digest('hex') };
  } catch {
    cached = null;
  }
  return cached;
}

/** Single-quote for POSIX sh. */
export function shQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function trimBase(baseUrl: string): string {
  return baseUrl.replace(/\/+$/, '');
}

/**
 * The command shown once when an agent is created. It pipes the install
 * script to a root shell with the token in that shell's environment only.
 */
export function installCommand(baseUrl: string, token: string, allowedPorts?: number[]): string {
  const env = [`BASTION_AGENT_TOKEN=${shQuote(token)}`];
  if (allowedPorts?.length && !(allowedPorts.length === 1 && allowedPorts[0] === 22)) {
    env.push(`BASTION_ALLOWED_PORTS=${shQuote(allowedPorts.join(','))}`);
  }
  return `curl -fsSL ${shQuote(trimBase(baseUrl) + AGENT_INSTALL_PATH)} | sudo env ${env.join(' ')} sh`;
}

/** The systemd unit the install script writes. `nodePath` is an absolute path. */
export function systemdUnit(nodePath: string): string {
  return `[Unit]
Description=BastionSSH connectivity agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=/etc/bastion-agent/agent.env
ExecStart=${nodePath} /opt/bastion-agent/bastion-agent.cjs
Restart=always
RestartSec=5
# The agent only needs outbound network and its loopback: run it unprivileged
# and without write access to the system.
DynamicUser=yes
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
PrivateTmp=yes
PrivateDevices=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
# AF_UNIX/AF_NETLINK: name resolution (nscd, systemd-resolved) may need them
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX AF_NETLINK
RestrictNamespaces=yes
LockPersonality=yes
CapabilityBoundingSet=
AmbientCapabilities=

[Install]
WantedBy=multi-user.target
`;
}

/** The install script served at {@link AGENT_INSTALL_PATH}. */
export function installScript(baseUrl: string, bundleSha256: string): string {
  const base = trimBase(baseUrl);
  // The unit is rendered with a placeholder the script swaps for `command -v node`
  const unit = systemdUnit('@NODE@');
  return `#!/bin/sh
# BastionSSH connectivity agent installer, generated by ${base}
#
# Usage (as shown once when the agent was created):
#   curl -fsSL ${base}${AGENT_INSTALL_PATH} | sudo env BASTION_AGENT_TOKEN=bsa_... sh
#
# Optional: BASTION_ALLOWED_PORTS=22,2222 — local ports the app may reach (default 22).
set -eu

BASTION_URL=${shQuote(base)}
AGENT_SHA256=${shQuote(bundleSha256)}

fail() { echo "bastion-agent install: $*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || fail "run as root (pipe to 'sudo env ... sh')"
command -v systemctl >/dev/null 2>&1 || fail "systemd is required"

TOKEN="\${BASTION_AGENT_TOKEN:-}"
case "$TOKEN" in
  bsa_*) ;;
  *) fail "set BASTION_AGENT_TOKEN to the token shown when the agent was created" ;;
esac
case "$TOKEN" in
  *[!A-Za-z0-9_-]*) fail "BASTION_AGENT_TOKEN contains unexpected characters" ;;
esac

PORTS="\${BASTION_ALLOWED_PORTS:-22}"
case "$PORTS" in
  ''|*[!0-9,]*) fail "BASTION_ALLOWED_PORTS must be a comma-separated list of port numbers" ;;
esac

INSECURE="\${BASTION_ALLOW_INSECURE:-}"
case "$INSECURE" in
  ''|0|1|true|false) ;;
  *) fail "BASTION_ALLOW_INSECURE must be 1 or unset" ;;
esac

NODE="$(command -v node || true)"
[ -n "$NODE" ] || fail "Node.js 18 or newer is required (node not found in PATH)"
NODE_MAJOR="$("$NODE" -p 'process.versions.node.split(".")[0]')"
[ "$NODE_MAJOR" -ge 18 ] || fail "Node.js 18 or newer is required (found $("$NODE" --version))"

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
if command -v curl >/dev/null 2>&1; then
  curl -fsSL "$BASTION_URL${AGENT_BUNDLE_PATH}" -o "$TMP"
elif command -v wget >/dev/null 2>&1; then
  wget -qO "$TMP" "$BASTION_URL${AGENT_BUNDLE_PATH}"
else
  fail "curl or wget is required"
fi

if command -v sha256sum >/dev/null 2>&1; then
  SUM="$(sha256sum "$TMP" | cut -d' ' -f1)"
else
  SUM="$(shasum -a 256 "$TMP" | cut -d' ' -f1)"
fi
[ "$SUM" = "$AGENT_SHA256" ] || fail "downloaded agent does not match the expected checksum"

install -d -m 0755 /opt/bastion-agent
install -m 0755 "$TMP" /opt/bastion-agent/bastion-agent.cjs

install -d -m 0700 /etc/bastion-agent
umask 077
{
  echo "BASTION_URL=$BASTION_URL"
  echo "BASTION_AGENT_TOKEN=$TOKEN"
  echo "BASTION_ALLOWED_PORTS=$PORTS"
  [ -z "$INSECURE" ] || echo "BASTION_ALLOW_INSECURE=$INSECURE"
} > /etc/bastion-agent/agent.env
chmod 0600 /etc/bastion-agent/agent.env
umask 022

cat > /etc/systemd/system/bastion-agent.service <<'UNIT'
${unit}UNIT
sed -i "s|@NODE@|$NODE|" /etc/systemd/system/bastion-agent.service

systemctl daemon-reload
systemctl enable bastion-agent >/dev/null
systemctl restart bastion-agent

echo "BastionSSH agent installed; allowing local port(s) $PORTS."
echo "Check it with: systemctl status bastion-agent  (logs: journalctl -u bastion-agent)"
`;
}
