import { describe, expect, it } from 'vitest';
import { generateCaddyfile, splitRedirects, type ProxySite } from './caddy.js';

const site = (over: Partial<ProxySite> = {}): ProxySite => ({
  app: 'site1',
  release: '20261005-120000-abcdef12',
  domains: ['site1.com', 'www.site1.com'],
  redirect_www: 'none',
  tls: 'auto',
  upstream: 'bastion-site1-20261005-120000-abcdef12:3000',
  ...over,
});

describe('Caddyfile generation', () => {
  it('serves every app through its current container, apps in name order', () => {
    const text = generateCaddyfile([site({ app: 'zeta', domains: ['zeta.io'], upstream: 'bastion-zeta-r1:8080', release: 'r1' }), site()]);
    expect(text).toBe(
      [
        '# Generated by bastionctl from apps/*/bastion.yml. Do not edit: it is rewritten on every deploy.',
        '',
        '{',
        '\tadmin localhost:2019',
        '}',
        '',
        '# app site1, release 20261005-120000-abcdef12',
        'site1.com, www.site1.com {',
        '\tencode zstd gzip',
        '\treverse_proxy bastion-site1-20261005-120000-abcdef12:3000',
        '}',
        '',
        '# app zeta, release r1',
        'zeta.io {',
        '\tencode zstd gzip',
        '\treverse_proxy bastion-zeta-r1:8080',
        '}',
        '',
      ].join('\n'),
    );
  });

  it('redirects www to the apex, or the other way, only where both are listed', () => {
    expect(splitRedirects(['a.com', 'www.a.com', 'www.b.com'], 'apex')).toEqual({ served: ['a.com', 'www.b.com'], redirects: [['www.a.com', 'a.com']] });
    expect(splitRedirects(['a.com', 'www.a.com', 'b.com'], 'www')).toEqual({ served: ['www.a.com', 'b.com'], redirects: [['a.com', 'www.a.com']] });
    expect(splitRedirects(['a.com', 'www.a.com'], 'none')).toEqual({ served: ['a.com', 'www.a.com'], redirects: [] });

    const text = generateCaddyfile([site({ redirect_www: 'apex', tls: 'internal' })]);
    expect(text).toContain('site1.com {\n\ttls internal\n\tencode zstd gzip\n\treverse_proxy bastion-site1-20261005-120000-abcdef12:3000\n}');
    // The redirect is served over HTTPS too, with the same certificate settings
    expect(text).toContain('www.site1.com {\n\ttls internal\n\tredir https://site1.com{uri} permanent\n}');
  });

  it('writes each tls mode', () => {
    expect(generateCaddyfile([site({ tls: 'staging' })])).toContain('\ttls {\n\t\tca https://acme-staging-v02.api.letsencrypt.org/directory\n\t}');
    expect(generateCaddyfile([site({ tls: 'dns:cloudflare' })])).toContain('\ttls {\n\t\tdns cloudflare {env.CLOUDFLARE_API_TOKEN}\n\t}');
    expect(generateCaddyfile([site({ tls: { cert: 'certs/site.pem', key: 'certs/site.key' } })])).toContain(
      '\ttls /bastion-proxy/certs/site1/cert.pem /bastion-proxy/certs/site1/key.pem',
    );
    expect(generateCaddyfile([site()])).not.toContain('tls');
  });

  it('has only the global block with no apps', () => {
    expect(generateCaddyfile([])).toBe('# Generated by bastionctl from apps/*/bastion.yml. Do not edit: it is rewritten on every deploy.\n\n{\n\tadmin localhost:2019\n}\n');
  });
});
