import { describe, expect, it } from 'vitest';
import { generateCaddyfile, splitRedirects, type ProxySite } from './caddy.js';

/** The global block in Caddy mode: loopback ports from the front, PROXY headers from it, our own HTTP redirect. */
const GLOBAL = [
  '# Generated by bastionctl from apps/*/bastion.yml. Do not edit: it is rewritten on every deploy.',
  '',
  '{',
  '\tadmin localhost:{$BASTION_ADMIN_PORT:2019}',
  '\thttp_port {$BASTION_HTTP_PORT:80}',
  '\thttps_port {$BASTION_HTTPS_PORT:443}',
  '\tdefault_bind 127.0.0.1',
  '\tgrace_period 10s',
  '\tskip_install_trust',
  '\tauto_https disable_redirects',
  '\tservers {',
  '\t\tlistener_wrappers {',
  '\t\t\tproxy_protocol {',
  '\t\t\t\ttimeout 5s',
  '\t\t\t\tallow 127.0.0.1/32',
  '\t\t\t}',
  '\t\t\ttls',
  '\t\t}',
  '\t\tprotocols h1 h2',
  '\t}',
  '}',
  '',
  'http:// {',
  '\tredir https://{host}{uri} permanent',
  '}',
];

const site = (over: Partial<ProxySite> = {}): ProxySite => ({
  app: 'site1',
  release: '20261005-120000-abcdef12',
  domains: ['site1.com', 'www.site1.com'],
  redirect_www: 'none',
  tls: 'auto',
  upstream: 'bastion-site1-live-3000:3000',
  ...over,
});

describe('Caddyfile generation', () => {
  it('serves every app through its live alias, apps in name order, with no release in the text', () => {
    const text = generateCaddyfile([site({ app: 'zeta', domains: ['zeta.io'], upstream: 'bastion-zeta-live-8080:8080', release: 'r1' }), site()]);
    expect(text).toBe(
      [
        ...GLOBAL,
        '',
        '# app site1',
        'site1.com, www.site1.com {',
        '\tencode zstd gzip',
        '\treverse_proxy bastion-site1-live-3000:3000 {',
        '\t\tlb_try_duration 5s',
        '\t}',
        '}',
        '',
        '# app zeta',
        'zeta.io {',
        '\tencode zstd gzip',
        '\treverse_proxy bastion-zeta-live-8080:8080 {',
        '\t\tlb_try_duration 5s',
        '\t}',
        '}',
        '',
      ].join('\n'),
    );
    // Another release on the same port is the same file: a deploy then needs no reload
    expect(generateCaddyfile([site({ release: '20261006-090000-12345678' })])).toBe(generateCaddyfile([site()]));
  });

  it('redirects www to the apex, or the other way, only where both are listed', () => {
    expect(splitRedirects(['a.com', 'www.a.com', 'www.b.com'], 'apex')).toEqual({ served: ['a.com', 'www.b.com'], redirects: [['www.a.com', 'a.com']] });
    expect(splitRedirects(['a.com', 'www.a.com', 'b.com'], 'www')).toEqual({ served: ['www.a.com', 'b.com'], redirects: [['a.com', 'www.a.com']] });
    expect(splitRedirects(['a.com', 'www.a.com'], 'none')).toEqual({ served: ['a.com', 'www.a.com'], redirects: [] });

    const text = generateCaddyfile([site({ redirect_www: 'apex', tls: 'internal' })]);
    expect(text).toContain('site1.com {\n\ttls internal\n\tencode zstd gzip\n\treverse_proxy bastion-site1-live-3000:3000 {\n\t\tlb_try_duration 5s\n\t}\n}');
    // The redirect is served over HTTPS too, with the same certificate settings
    expect(text).toContain('www.site1.com {\n\ttls internal\n\tredir https://site1.com{uri} permanent\n}');
  });

  it('writes each tls mode', () => {
    expect(generateCaddyfile([site({ tls: 'staging' })])).toContain('\ttls {\n\t\tca https://acme-staging-v02.api.letsencrypt.org/directory\n\t}');
    expect(generateCaddyfile([site({ tls: 'dns:cloudflare' })])).toContain('\ttls {\n\t\tdns cloudflare {env.CLOUDFLARE_API_TOKEN}\n\t}');
    expect(generateCaddyfile([site({ tls: { cert: 'certs/site.pem', key: 'certs/site.key' } })])).toContain(
      '\ttls /bastion-proxy/certs/site1/cert.pem /bastion-proxy/certs/site1/key.pem',
    );
    expect(generateCaddyfile([site()]).split('# app site1')[1]).not.toContain('tls');
  });

  it('has only the global block with no apps', () => {
    expect(generateCaddyfile([])).toBe(GLOBAL.join('\n') + '\n');
  });
});
