import net from 'node:net';
import type { DeployAppConfig, DeployProxyMode } from '@smt/shared';

/**
 * The Caddyfile (deployments spec §5 step 6, §6), generated from every app on
 * the server: one site block per app serving its domains through the app's
 * live alias, plus redirect blocks for `redirect_www`. Never hand-edited — it
 * is regenerated on every deploy, rollback, config change and `proxy apply`;
 * a deploy reloads Caddy only when the text changed (`proxy apply` always
 * does). Every value placed in it was validated first (domains, app names, release
 * ids, ports, provider names), so nothing user-written can open a new
 * directive.
 *
 * In nginx mode (nginx.ts) the host's nginx terminates TLS: every site is
 * plain `http://`, automatic HTTPS is off, and the forwarded-for headers are
 * trusted from the host's nginx only — the addresses its connections reach
 * Caddy from (`trusted`: the gateway of the bastion-apps network, which the
 * port published on 127.0.0.1 forwards from, and 127.0.0.1). Any other
 * sender, such as an app's container on the same network, has its
 * X-Forwarded-For replaced by its own address before an app sees it.
 */

/** Where the proxy container sees `<root>/proxy`. */
export const PROXY_MOUNT = '/bastion-proxy';
const STAGING_CA = 'https://acme-staging-v02.api.letsencrypt.org/directory';
/** How long Caddy keeps trying an app's upstream for one request (GETs, and any request that never reached it). */
const RETRY_DURATION = '5s';

export interface ProxySite {
  app: string;
  release: string;
  domains: string[];
  redirect_www: DeployAppConfig['redirect_www'];
  tls: DeployAppConfig['tls'];
  /** `bastion-<app>-live-<port>:<port>`: the app's live alias on the bastion-live network. */
  upstream: string;
}

/** Where `tls: { cert, key }` files are copied for the proxy (relative to `<root>/proxy`). */
export function certPaths(app: string): { cert: string; key: string } {
  return { cert: `certs/${app}/cert.pem`, key: `certs/${app}/key.pem` };
}

/** The env variable a `dns:<provider>` token is read from, in `<root>/proxy/.env`. */
export function dnsTokenVariable(provider: string): string {
  return `${provider.toUpperCase()}_API_TOKEN`;
}

function tlsLines(site: ProxySite): string[] {
  const { tls } = site;
  if (typeof tls !== 'string') {
    const paths = certPaths(site.app);
    return [`\ttls ${PROXY_MOUNT}/${paths.cert} ${PROXY_MOUNT}/${paths.key}`];
  }
  if (tls === 'auto') return [];
  if (tls === 'internal') return ['\ttls internal'];
  if (tls === 'staging') return ['\ttls {', `\t\tca ${STAGING_CA}`, '\t}'];
  const provider = tls.slice('dns:'.length);
  return ['\ttls {', `\t\tdns ${provider} {env.${dnsTokenVariable(provider)}}`, '\t}'];
}

/** Which domains redirect where under `redirect_www`, and which are served. */
export function splitRedirects(domains: readonly string[], mode: DeployAppConfig['redirect_www']): { served: string[]; redirects: Array<[from: string, to: string]> } {
  const redirects: Array<[string, string]> = [];
  if (mode === 'apex') {
    for (const d of domains) if (d.startsWith('www.') && domains.includes(d.slice(4))) redirects.push([d, d.slice(4)]);
  } else if (mode === 'www') {
    for (const d of domains) if (!d.startsWith('www.') && !d.startsWith('*.') && domains.includes(`www.${d}`)) redirects.push([d, `www.${d}`]);
  }
  const from = new Set(redirects.map(([f]) => f));
  return { served: domains.filter((d) => !from.has(d)), redirects };
}

/** Where the host's nginx reaches Caddy from when nothing more is known: loopback only. */
export const NGINX_LOOPBACK = '127.0.0.1/32';

/** An IP address or CIDR range, checked: only these go into `trusted_proxies`. */
export function isAddressRange(value: string): boolean {
  const [address, prefix, ...rest] = value.split('/');
  const family = net.isIP(address ?? '');
  if (family === 0 || rest.length > 0) return false;
  if (prefix === undefined) return true;
  return /^\d{1,3}$/.test(prefix) && Number(prefix) <= (family === 4 ? 32 : 128);
}

export function generateCaddyfile(sites: readonly ProxySite[], mode: DeployProxyMode = 'caddy', trusted: readonly string[] = [NGINX_LOOPBACK]): string {
  const behindNginx = mode === 'nginx';
  const proxies = [...new Set(trusted)];
  if (behindNginx && (proxies.length === 0 || !proxies.every(isAddressRange))) throw new Error(`Invalid trusted proxy addresses: ${proxies.join(' ')}`);
  const out: string[] = [
    '# Generated by bastionctl from apps/*/bastion.yml. Do not edit: it is rewritten on every deploy.',
    '',
    '{',
    '\tadmin localhost:2019',
    ...(behindNginx ? ['\tauto_https off', '\tservers {', `\t\ttrusted_proxies static ${proxies.join(' ')}`, '\t}'] : []),
    '}',
  ];
  const address = (domain: string) => (behindNginx ? `http://${domain}` : domain);
  for (const site of [...sites].sort((a, b) => a.app.localeCompare(b.app))) {
    const { served, redirects } = splitRedirects(site.domains, site.redirect_www);
    const tls = behindNginx ? [] : tlsLines(site);
    // No release in here: a deploy that only moves the live alias leaves this file as it is
    out.push('', `# app ${site.app}`);
    if (served.length > 0) {
      out.push(
        `${served.map(address).join(', ')} {`,
        ...tls,
        '\tencode zstd gzip',
        // While a deploy stops the previous container, a request it dropped is tried again on the new one
        `\treverse_proxy ${site.upstream} {`,
        `\t\tlb_try_duration ${RETRY_DURATION}`,
        '\t}',
        '}',
      );
    }
    for (const [from, to] of redirects) {
      out.push('', `${address(from)} {`, ...tls, `\tredir https://${to}{uri} permanent`, '}');
    }
  }
  return out.join('\n') + '\n';
}
