import type { DeployAppConfig, DeployProxyMode } from '@smt/shared';

/**
 * The Caddyfile (deployments spec §5 step 6, §6), generated from every app on
 * the server: one site block per app serving its domains through its current
 * container, plus redirect blocks for `redirect_www`. Never hand-edited — it
 * is rewritten on every deploy, rollback, config change and `proxy apply`.
 * Every value placed in it was validated first (domains, app names, release
 * ids, ports, provider names), so nothing user-written can open a new
 * directive.
 *
 * In nginx mode (nginx.ts) the host's nginx terminates TLS: every site is
 * plain `http://`, automatic HTTPS is off, and the forwarded-for headers of
 * the proxy in front (reaching Caddy from a private address) are trusted.
 */

/** Where the proxy container sees `<root>/proxy`. */
export const PROXY_MOUNT = '/bastion-proxy';
const STAGING_CA = 'https://acme-staging-v02.api.letsencrypt.org/directory';

export interface ProxySite {
  app: string;
  release: string;
  domains: string[];
  redirect_www: DeployAppConfig['redirect_www'];
  tls: DeployAppConfig['tls'];
  /** `bastion-<app>-<release>:<port>` on the bastion-apps network. */
  upstream: string;
}

/** Where `tls: { cert, key }` files are copied for the proxy (relative to `<root>/proxy`). */
export function certPaths(app: string): { cert: string; key: string } {
  return { cert: `certs/${app}/cert.pem`, key: `certs/${app}/key.pem` };
}

/** The env variable a `dns:<provider>` token is read from, in `<root>/proxy/.env`. */
export function dnsTokenVariable(provider: string): string {
  return `${provider.toUpperCase()}_API_TOKEN`;
}

function tlsLines(site: ProxySite): string[] {
  const { tls } = site;
  if (typeof tls !== 'string') {
    const paths = certPaths(site.app);
    return [`\ttls ${PROXY_MOUNT}/${paths.cert} ${PROXY_MOUNT}/${paths.key}`];
  }
  if (tls === 'auto') return [];
  if (tls === 'internal') return ['\ttls internal'];
  if (tls === 'staging') return ['\ttls {', `\t\tca ${STAGING_CA}`, '\t}'];
  const provider = tls.slice('dns:'.length);
  return ['\ttls {', `\t\tdns ${provider} {env.${dnsTokenVariable(provider)}}`, '\t}'];
}

/** Which domains redirect where under `redirect_www`, and which are served. */
export function splitRedirects(domains: readonly string[], mode: DeployAppConfig['redirect_www']): { served: string[]; redirects: Array<[from: string, to: string]> } {
  const redirects: Array<[string, string]> = [];
  if (mode === 'apex') {
    for (const d of domains) if (d.startsWith('www.') && domains.includes(d.slice(4))) redirects.push([d, d.slice(4)]);
  } else if (mode === 'www') {
    for (const d of domains) if (!d.startsWith('www.') && !d.startsWith('*.') && domains.includes(`www.${d}`)) redirects.push([d, `www.${d}`]);
  }
  const from = new Set(redirects.map(([f]) => f));
  return { served: domains.filter((d) => !from.has(d)), redirects };
}

export function generateCaddyfile(sites: readonly ProxySite[], mode: DeployProxyMode = 'caddy'): string {
  const behindNginx = mode === 'nginx';
  const out: string[] = [
    '# Generated by bastionctl from apps/*/bastion.yml. Do not edit: it is rewritten on every deploy.',
    '',
    '{',
    '\tadmin localhost:2019',
    ...(behindNginx ? ['\tauto_https off', '\tservers {', '\t\ttrusted_proxies static private_ranges', '\t}'] : []),
    '}',
  ];
  const address = (domain: string) => (behindNginx ? `http://${domain}` : domain);
  for (const site of [...sites].sort((a, b) => a.app.localeCompare(b.app))) {
    const { served, redirects } = splitRedirects(site.domains, site.redirect_www);
    const tls = behindNginx ? [] : tlsLines(site);
    out.push('', `# app ${site.app}, release ${site.release}`);
    if (served.length > 0) {
      out.push(`${served.map(address).join(', ')} {`, ...tls, '\tencode zstd gzip', `\treverse_proxy ${site.upstream}`, '}');
    }
    for (const [from, to] of redirects) {
      out.push('', `${address(from)} {`, ...tls, `\tredir https://${to}{uri} permanent`, '}');
    }
  }
  return out.join('\n') + '\n';
}
