/**
 * Throwaway test PKI for the fake Kubernetes API server (fake-api.test-helper.ts),
 * generated once with openssl and valid for a century. Nothing here is used
 * outside tests. The server certificate names kube.test, localhost and
 * 127.0.0.1; `OTHER_CA` signed nothing here (for verification failures).
 */

export const CA_CERT = `-----BEGIN CERTIFICATE-----
MIIBpTCCAUugAwIBAgIUB1ZYwJVKznAHC40k20zGKvZ+j0owCgYIKoZIzj0EAwIw
HzEdMBsGA1UEAwwUYmFzdGlvbi10ZXN0LWt1YmUtY2EwIBcNMjYxMDAzMTE1MDE5
WhgPMjEyNjA5MDkxMTUwMTlaMB8xHTAbBgNVBAMMFGJhc3Rpb24tdGVzdC1rdWJl
LWNhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEhs4bXLJqIZz89UM+KSh9Qbaz
73bp+L5yfoogBbp1hVDOwPZuXok+VUHgPrSHwrtrdEpRXWXPUw8lE7XYUTwzw6Nj
MGEwHQYDVR0OBBYEFNnvkYSxXPe2TEvqKxwLHxVPhmHDMB8GA1UdIwQYMBaAFNnv
kYSxXPe2TEvqKxwLHxVPhmHDMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQD
AgEGMAoGCCqGSM49BAMCA0gAMEUCICD35gAUUetcczhsga7wzDBueAvqDp4N1ss/
XHx2Ie4SAiEAseVq1q+t7SuU/3fDUaO1V9+qFP5TfriDB1m9WByzLyo=
-----END CERTIFICATE-----
`;

export const SERVER_CERT = `-----BEGIN CERTIFICATE-----
MIIByDCCAW2gAwIBAgIUditOJtsyFLfpn7GDr/4njWzf4v0wCgYIKoZIzj0EAwIw
HzEdMBsGA1UEAwwUYmFzdGlvbi10ZXN0LWt1YmUtY2EwIBcNMjYxMDAzMTE1MDE5
WhgPMjEyNjA5MDkxMTUwMTlaMBkxFzAVBgNVBAMMDmt1YmUtYXBpc2VydmVyMFkw
EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEfaXmL29aFjODGkK7RX6lphixuUipT1sq
ZYiEfi1buzjysaWVXPbRYHBeWrntqYRxeEpsBtqWfDua25c7xr8L+aOBijCBhzAl
BgNVHREEHjAcgglrdWJlLnRlc3SCCWxvY2FsaG9zdIcEfwAAATATBgNVHSUEDDAK
BggrBgEFBQcDATAJBgNVHRMEAjAAMB0GA1UdDgQWBBTdC2Rpp/l4wxymsy2TwbHM
4putOTAfBgNVHSMEGDAWgBTZ75GEsVz3tkxL6iscCx8VT4ZhwzAKBggqhkjOPQQD
AgNJADBGAiEAzfxNBSnXjcHMLbQhe5Z6ye9LZirx31I+So6wwk2wCYsCIQCGEMfs
X6UtPPrfvSqFdtelW146VtfJPjobPKxtWCC0qw==
-----END CERTIFICATE-----
`;

export const CLIENT_CERT = `-----BEGIN CERTIFICATE-----
MIIBtzCCAVygAwIBAgIUditOJtsyFLfpn7GDr/4njWzf4v4wCgYIKoZIzj0EAwIw
HzEdMBsGA1UEAwwUYmFzdGlvbi10ZXN0LWt1YmUtY2EwIBcNMjYxMDAzMTE1MDE5
WhgPMjEyNjA5MDkxMTUwMTlaMDExFzAVBgNVBAoMDnN5c3RlbTptYXN0ZXJzMRYw
FAYDVQQDDA1iYXN0aW9uLWFkbWluMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
Lb4crQz88mPqyuyLcNmvdP4uxZ5NXbVTy7JyWr5RP1Nu1jYaa54fcffOt56FLa00
1bFBmaQO8PGwakinRxSsgKNiMGAwEwYDVR0lBAwwCgYIKwYBBQUHAwIwCQYDVR0T
BAIwADAdBgNVHQ4EFgQUhLsXC9XPEPX/p7Sfrdf5JlY/f9MwHwYDVR0jBBgwFoAU
2e+RhLFc97ZMS+orHAsfFU+GYcMwCgYIKoZIzj0EAwIDSQAwRgIhAM52kPJByqH6
zn2iheyXJyxDVpxmb6EUe52Ff51vRIN9AiEA1sRxPBh5pgu8tEasxm9i25zGceeG
ZoiHP2E17ESDxXI=
-----END CERTIFICATE-----
`;

export const OTHER_CA = `-----BEGIN CERTIFICATE-----
MIIBhjCCAS2gAwIBAgIUNQO1VA1fh2qCrZuTXxtIKWNLCI8wCgYIKoZIzj0EAwIw
GDEWMBQGA1UEAwwNc29tZS1vdGhlci1jYTAgFw0yNjEwMDMxMTUwMTlaGA8yMTI2
MDkwOTExNTAxOVowGDEWMBQGA1UEAwwNc29tZS1vdGhlci1jYTBZMBMGByqGSM49
AgEGCCqGSM49AwEHA0IABERJ1nauBTTRR+0aiESufHsBEq5om4V2CyllBut/SikE
MokX1lC5bulpmxmcCG2lO45oY4drsgwPd0S5DMgbGmajUzBRMB0GA1UdDgQWBBQA
HCFEe3wal4XFWa034Ar0TGg0GDAfBgNVHSMEGDAWgBQAHCFEe3wal4XFWa034Ar0
TGg0GDAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0cAMEQCIGVQiG3caBeM
K9aVvH6quVErOZ6LrZfUIYtCMbHqXiYgAiAq0tly3lZ1b/4yJuz90yeeP8eTtX9C
kB4FTO923516gQ==
-----END CERTIFICATE-----
`;

export const SERVER_KEY = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgRxyBewCLOBsxrn8z
bkhAQY7WP0TfSEJoqdq2iZmghQ2hRANCAAR9peYvb1oWM4MaQrtFfqWmGLG5SKlP
WypliIR+LVu7OPKxpZVc9tFgcF5aue2phHF4SmwG2pZ8O5rblzvGvwv5
-----END PRIVATE KEY-----
`;

export const CLIENT_KEY = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgbG45C0TWqkYzJRzR
OaLGV9WlMscQTCrHzJpObC4khPWhRANCAAQtvhytDPzyY+rK7Itw2a90/i7Fnk1d
tVPLsnJavlE/U27WNhprnh9x9863noUtrTTVsUGZpA7w8bBqSKdHFKyA
-----END PRIVATE KEY-----
`;
